deploy:
  runs-on: ubuntu-latest
  needs: test

  steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Download artifact for deployment
      uses: actions/download-artifact@v4
      with:
        name: cvdstodo

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v4
      with:
        app-name: 'cvdstodo'
        slot-name: 'production'
        package: 'target/*.jar'
